matrix:
  include:
    - language: java
      dist: trusty
      jdk:
        - openjdk8

    - language: objective-c
      os: osx
      osx_image: xcode11.5
      before_script:
        - make install_buck
        - make setup
      script:
        - make build
