load("//Config:configs.bzl", "app_binary_configs", "library_configs", "info_plist_substitutions")

APP_NAME = "BuckFirebaseSample"

apple_resource(
  name = 'BuckFirebaseSampleResources',
  files = glob(['LaunchScreen.storyboard',]),
  dirs = [],
)

apple_library(
  name = "BuckFirebaseSampleAppLibrary",
  configs = library_configs(),
  srcs = glob(['*.swift']),
  deps = [':BuckFirebaseSampleResources'],
)

apple_binary(
    name = "BuckFirebaseSampleAppBinary",
    deps = [':BuckFirebaseSampleAppLibrary'],
    configs = app_binary_configs(APP_NAME),
    srcs = ["BuckSupportFiles/Dummy.swift",],
)

apple_bundle(
  name = 'BuckFirebaseSampleApp',
  binary = ':BuckFirebaseSampleAppBinary',
  extension = 'app',
  info_plist = 'Info.plist',
  info_plist_substitutions = info_plist_substitutions(APP_NAME),
)

apple_package(
  name = 'BuckFirebaseSampleAppPackage',
  bundle = ':BuckFirebaseSampleApp',
)